# Results

In [20]:
import pandas as pd
import numpy as np

# Symbolic regression

In [22]:
setts = np.array([x.split(',') for x in df['Unnamed: 0']])
setts[:,0]

array(['10', '50', '100', '10', '50', '100', '10', '50', '100', '10', '50',
       '100', '10', '50', '100'],
      dtype='<U3')

## Point mutation

In [52]:
df = pd.read_csv('scripts/out/symreg_pm.csv')
setts = np.array([[int(y) for y in x.split(',')] for x in df['Unnamed: 0']])
df['nodes'] = setts[:, 0]
df['gems'] = setts[:, 1]
df['uses'] = setts[:, 2]
df[['nodes', 'gems', 'uses', 'best fitness', 'mean of best individual', 'std of best indvidiual']][((df['uses'] == 0) & (df['gems'] == 0)) |((df['uses'] == 30) & (df['gems'] != 0))]

,nodes,gems,uses,best fitness,mean of best individual,std of best indvidiual
0,10,0,0,0.148973,0.359569,0.087830
1,50,0,0,0.000000,0.282891,0.116849
2,100,0,0,0.167763,0.307991,0.077190
6,10,5,30,0.199623,0.397679,0.099685
7,50,5,30,0.053798,0.295439,0.116299
8,100,5,30,0.198590,0.324479,0.075607
12,10,10,30,0.164879,0.398036,0.084242
13,50,10,30,0.163178,0.306941,0.101370
14,100,10,30,0.113260,0.347173,0.084432

## Single mutation all

In [53]:
df = pd.read_csv('scripts/out/symreg_sm_all.csv')
setts = np.array([[int(y) for y in x.split(',')] for x in df['Unnamed: 0']])
df['nodes'] = setts[:, 0]
df['gems'] = setts[:, 1]
df['uses'] = setts[:, 2]
df[['nodes', 'gems', 'uses', 'best fitness', 'mean of best individual', 'std of best indvidiual']][((df['uses'] == 0) & (df['gems'] == 0)) |((df['uses'] == 30) & (df['gems'] != 0))]

,nodes,gems,uses,best fitness,mean of best individual,std of best indvidiual
0,10,0,0,0.090185,0.372760,0.122868
1,50,0,0,0.000000,0.271078,0.128078
2,100,0,0,0.121879,0.314480,0.102917
6,10,5,30,0.117614,0.365970,0.108160
7,50,5,30,0.057092,0.311986,0.128519
8,100,5,30,0.175893,0.351501,0.091809
12,10,10,30,0.000000,0.340701,0.148785
13,50,10,30,0.000000,0.286671,0.121506
14,100,10,30,0.054159,0.310510,0.120797

## Single mutation active

In [54]:
df = pd.read_csv('scripts/out/symreg_sm_active.csv')
setts = np.array([[int(y) for y in x.split(',')] for x in df['Unnamed: 0']])
df['nodes'] = setts[:, 0]
df['gems'] = setts[:, 1]
df['uses'] = setts[:, 2]
df[['nodes', 'gems', 'uses', 'best fitness', 'mean of best individual', 'std of best indvidiual']][((df['uses'] == 0) & (df['gems'] == 0)) |((df['uses'] == 30) & (df['gems'] != 0))]

,nodes,gems,uses,best fitness,mean of best individual,std of best indvidiual
0,10,0,0,0.090185,0.372760,0.122868
1,50,0,0,0.000000,0.271078,0.128078
2,100,0,0,0.121879,0.314480,0.102917
6,10,5,30,0.208486,0.364766,0.080324
7,50,5,30,0.043247,0.289751,0.129461
8,100,5,30,0.193370,0.374188,0.099228
12,10,10,30,0.177179,0.329473,0.084030
13,50,10,30,0.164081,0.297420,0.094156
14,100,10,30,0.167493,0.375127,0.093290

## Probabilistic mutation all

In [55]:
df = pd.read_csv('scripts/out/symreg_probm_all.csv')
setts = np.array([[int(y) for y in x.split(',')] for x in df['Unnamed: 0']])
df['nodes'] = setts[:, 0]
df['gems'] = setts[:, 1]
df['uses'] = setts[:, 2]
df[['nodes', 'gems', 'uses', 'best fitness', 'mean of best individual', 'std of best indvidiual']][((df['uses'] == 0) & (df['gems'] == 0)) |((df['uses'] == 30) & (df['gems'] != 0))]

,nodes,gems,uses,best fitness,mean of best individual,std of best indvidiual
0,10,0,0,0.117614,0.219439,0.079739
1,50,0,0,0.120955,0.211337,0.059655
2,100,0,0,0.167763,0.254630,0.080073
6,10,5,30,0.000000,0.200630,0.114505
7,50,5,30,0.120955,0.211337,0.059655
8,100,5,30,0.167763,0.254630,0.080073
12,10,10,30,0.117614,0.208984,0.073757
13,50,10,30,0.120955,0.211337,0.059655
14,100,10,30,0.167763,0.254630,0.080073

## Probabilistic mutation active

In [56]:
df = pd.read_csv('scripts/out/symreg_probm_active.csv')
setts = np.array([[int(y) for y in x.split(',')] for x in df['Unnamed: 0']])
df['nodes'] = setts[:, 0]
df['gems'] = setts[:, 1]
df['uses'] = setts[:, 2]
df[['nodes', 'gems', 'uses', 'best fitness', 'mean of best individual', 'std of best indvidiual']][((df['uses'] == 0) & (df['gems'] == 0)) |((df['uses'] == 30) & (df['gems'] != 0))]

,nodes,gems,uses,best fitness,mean of best individual,std of best indvidiual
0,10,0,0,0.117614,0.219439,0.079739
1,50,0,0,0.120955,0.211337,0.059655
2,100,0,0,0.167763,0.254630,0.080073
6,10,5,30,0.000000,0.195192,0.094030
7,50,5,30,0.000000,0.187302,0.114837
8,100,5,30,0.000000,0.218864,0.102923
12,10,10,30,0.000000,0.223514,0.109071
13,50,10,30,0.000000,0.196622,0.112826
14,100,10,30,0.000000,0.238097,0.108348